{
  "_args": [
    [
      "failing-line@0.1.0",
      "C:\\Projetos\\desafio-ninja"
    ]
  ],
  "_development": true,
  "_from": "failing-line@0.1.0",
  "_id": "failing-line@0.1.0",
  "_inBundle": false,
  "_integrity": "sha1-/BT9jwgBpkHxFE5OiTAQq2/qJJY=",
  "_location": "/failing-line",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "failing-line@0.1.0",
    "name": "failing-line",
    "escapedName": "failing-line",
    "rawSpec": "0.1.0",
    "saveSpec": null,
    "fetchSpec": "0.1.0"
  },
  "_requiredBy": [
    "/failing-code"
  ],
  "_resolved": "https://registry.npmjs.org/failing-line/-/failing-line-0.1.0.tgz",
  "_spec": "0.1.0",
  "_where": "C:\\Projetos\\desafio-ninja",
  "author": {
    "name": "azer"
  },
  "bugs": {
    "url": "https://github.com/azer/failing-line/issues"
  },
  "description": "Return the line number and filename of failing line from given error object",
  "devDependencies": {
    "tape": "*"
  },
  "homepage": "https://github.com/azer/failing-line#readme",
  "keywords": [
    "error",
    "fail",
    "failing",
    "line number"
  ],
  "license": "BSD",
  "main": "index.js",
  "name": "failing-line",
  "repository": {
    "url": "git+ssh://git@github.com/azer/failing-line.git",
    "type": "git"
  },
  "scripts": {
    "test": "node test.js"
  },
  "version": "0.1.0"
}
